  notify-email:
    name: "📧 Email Notification"
    runs-on: ubuntu-latest
    needs: [linting, snyk-security, build-and-test, deploy]
    if: always()
    steps:
    - name: Create status summary
      id: status-summary
      run: |
        # Get the status of each job
        LINT_STATUS="${{ needs.linting.result }}"
        SNYK_STATUS="${{ needs.snyk-security.result }}"
        BUILD_STATUS="${{ needs.build-and-test.result }}"
        DEPLOY_STATUS="${{ needs.deploy.result }}"
        
        # Set default values if jobs were skipped
        if [ -z "$LINT_STATUS" ]; then LINT_STATUS="skipped"; fi
        if [ -z "$SNYK_STATUS" ]; then SNYK_STATUS="skipped"; fi
        if [ -z "$BUILD_STATUS" ]; then BUILD_STATUS="skipped"; fi
        if [ -z "$DEPLOY_STATUS" ]; then DEPLOY_STATUS="skipped"; fi
        
        echo "LINT_STATUS=$LINT_STATUS" >> $GITHUB_OUTPUT
        echo "SNYK_STATUS=$SNYK_STATUS" >> $GITHUB_OUTPUT
        echo "BUILD_STATUS=$BUILD_STATUS" >> $GITHUB_OUTPUT
        echo "DEPLOY_STATUS=$DEPLOY_STATUS" >> $GITHUB_OUTPUT
        
        # Determine overall status
        if [ "$LINT_STATUS" = "success" ] && [ "$SNYK_STATUS" = "success" ] && [ "$BUILD_STATUS" = "success" ] && [ "$DEPLOY_STATUS" = "success" ]; then
          echo "OVERALL_STATUS=SUCCESS" >> $GITHUB_OUTPUT
        else
          echo "OVERALL_STATUS=FAILED" >> $GITHUB_OUTPUT
        fi

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'CI/CD Status: ${{ steps.status-summary.outputs.OVERALL_STATUS }} - ${{ github.workflow }}'
        body: |
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }
              .container { max-width: 700px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 25px; border-radius: 8px; text-align: center; }
              .status-pass { color: #28a745; font-weight: bold; }
              .status-fail { color: #dc3545; font-weight: bold; }
              .status-skipped { color: #6c757d; font-weight: bold; }
              .test-result { margin: 15px 0; padding: 15px; border-radius: 8px; border-left: 5px solid; }
              .passed { border-color: #28a745; background: #f8fff9; }
              .failed { border-color: #dc3545; background: #fff5f5; }
              .skipped { border-color: #6c757d; background: #f8f9fa; }
              .summary { background: #e8f4fd; padding: 20px; border-radius: 8px; margin: 25px 0; }
              .badge { display: inline-block; padding: 5px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; margin-left: 10px; }
              .badge-success { background: #28a745; color: white; }
              .badge-danger { background: #dc3545; color: white; }
              .badge-secondary { background: #6c757d; color: white; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🚀 CI/CD Pipeline Status Report</h1>
                <h2>${{ github.workflow }}</h2>
                <h3>Overall Status: 
                  <span class="${{ steps.status-summary.outputs.OVERALL_STATUS == 'SUCCESS' && 'status-pass' || 'status-fail' }}">
                    ${{ steps.status-summary.outputs.OVERALL_STATUS }}
                  </span>
                </h3>
              </div>

              <div class="summary">
                <h3>📊 Deployment Summary</h3>
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>Application:</strong></td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;">${{ env.AZURE_WEBAPP_NAME }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>Triggered by:</strong></td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;">${{ github.actor }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>Branch:</strong></td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;">${{ github.ref }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>Commit:</strong></td>
                    <td style="padding: 8px; border-bottom: 1px solid #ddd;">${{ github.sha }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px;"><strong>Run ID:</strong></td>
                    <td style="padding: 8px;">${{ github.run_id }}</td>
                  </tr>
                </table>
              </div>

              <h3>🔍 Detailed Test Results</h3>

              <!-- Linter Status -->
              <div class="test-result ${{ steps.status-summary.outputs.LINT_STATUS == 'success' && 'passed' || steps.status-summary.outputs.LINT_STATUS == 'failure' && 'failed' || 'skipped' }}">
                <h4>🔍 Code Linting & Quality Analysis</h4>
                <p>
                  <strong>Status:</strong> 
                  <span class="${{ steps.status-summary.outputs.LINT_STATUS == 'success' && 'status-pass' || steps.status-summary.outputs.LINT_STATUS == 'failure' && 'status-fail' || 'status-skipped' }}">
                    ${{ steps.status-summary.outputs.LINT_STATUS == 'success' && '✅ PASSED' || steps.status-summary.outputs.LINT_STATUS == 'failure' && '❌ FAILED' || '⚪ SKIPPED' }}
                  </span>
                  <span class="${{ steps.status-summary.outputs.LINT_STATUS == 'success' && 'badge badge-success' || steps.status-summary.outputs.LINT_STATUS == 'failure' && 'badge badge-danger' || 'badge badge-secondary' }}">
                    ${{ steps.status-summary.outputs.LINT_STATUS == 'success' && 'PASS' || steps.status-summary.outputs.LINT_STATUS == 'failure' && 'FAIL' || 'SKIPPED' }}
                  </span>
                </p>
                <p>Code formatting, style consistency, and quality standards verification</p>
                ${{ steps.status-summary.outputs.LINT_STATUS == 'success' && '<p>✅ All code quality checks passed successfully</p>' || '' }}
                ${{ steps.status-summary.outputs.LINT_STATUS == 'failure' && '<p>❌ Code formatting or quality issues detected</p>' || '' }}
              </div>

              <!-- Snyk Security Status -->
              <div class="test-result ${{ steps.status-summary.outputs.SNYK_STATUS == 'success' && 'passed' || steps.status-summary.outputs.SNYK_STATUS == 'failure' && 'failed' || 'skipped' }}">
                <h4>🔒 Snyk Security Vulnerability Scan</h4>
                <p>
                  <strong>Status:</strong> 
                  <span class="${{ steps.status-summary.outputs.SNYK_STATUS == 'success' && 'status-pass' || steps.status-summary.outputs.SNYK_STATUS == 'failure' && 'status-fail' || 'status-skipped' }}">
                    ${{ steps.status-summary.outputs.SNYK_STATUS == 'success' && '✅ PASSED' || steps.status-summary.outputs.SNYK_STATUS == 'failure' && '❌ FAILED' || '⚪ SKIPPED' }}
                  </span>
                  <span class="${{ steps.status-summary.outputs.SNYK_STATUS == 'success' && 'badge badge-success' || steps.status-summary.outputs.SNYK_STATUS == 'failure' && 'badge badge-danger' || 'badge badge-secondary' }}">
                    ${{ steps.status-summary.outputs.SNYK_STATUS == 'success' && 'PASS' || steps.status-summary.outputs.SNYK_STATUS == 'failure' && 'FAIL' || 'SKIPPED' }}
                  </span>
                </p>
                <p>Dependency vulnerability scanning and security assessment</p>
                ${{ steps.status-summary.outputs.SNYK_STATUS == 'success' && '<p>✅ No high severity vulnerabilities detected</p>' || '' }}
                ${{ steps.status-summary.outputs.SNYK_STATUS == 'failure' && '<p>❌ Security vulnerabilities found - immediate review required</p>' || '' }}
              </div>

              <!-- Build & Test Status -->
              <div class="test-result ${{ steps.status-summary.outputs.BUILD_STATUS == 'success' && 'passed' || steps.status-summary.outputs.BUILD_STATUS == 'failure' && 'failed' || 'skipped' }}">
                <h4>🏗️ Build & Unit Tests</h4>
                <p>
                  <strong>Status:</strong> 
                  <span class="${{ steps.status-summary.outputs.BUILD_STATUS == 'success' && 'status-pass' || steps.status-summary.outputs.BUILD_STATUS == 'failure' && 'status-fail' || 'status-skipped' }}">
                    ${{ steps.status-summary.outputs.BUILD_STATUS == 'success' && '✅ PASSED' || steps.status-summary.outputs.BUILD_STATUS == 'failure' && '❌ FAILED' || '⚪ SKIPPED' }}
                  </span>
                  <span class="${{ steps.status-summary.outputs.BUILD_STATUS == 'success' && 'badge badge-success' || steps.status-summary.outputs.BUILD_STATUS == 'failure' && 'badge badge-danger' || 'badge badge-secondary' }}">
                    ${{ steps.status-summary.outputs.BUILD_STATUS == 'success' && 'PASS' || steps.status-summary.outputs.BUILD_STATUS == 'failure' && 'FAIL' || 'SKIPPED' }}
                  </span>
                </p>
                <p>Application compilation, testing, and artifact preparation</p>
              </div>

              <!-- Deployment Status -->
              <div class="test-result ${{ steps.status-summary.outputs.DEPLOY_STATUS == 'success' && 'passed' || steps.status-summary.outputs.DEPLOY_STATUS == 'failure' && 'failed' || 'skipped' }}">
                <h4>🚀 Azure App Service Deployment</h4>
                <p>
                  <strong>Status:</strong> 
                  <span class="${{ steps.status-summary.outputs.DEPLOY_STATUS == 'success' && 'status-pass' || steps.status-summary.outputs.DEPLOY_STATUS == 'failure' && 'status-fail' || 'status-skipped' }}">
                    ${{ steps.status-summary.outputs.DEPLOY_STATUS == 'success' && '✅ PASSED' || steps.status-summary.outputs.DEPLOY_STATUS == 'failure' && '❌ FAILED' || '⚪ SKIPPED' }}
                  </span>
                  <span class="${{ steps.status-summary.outputs.DEPLOY_STATUS == 'success' && 'badge badge-success' || steps.status-summary.outputs.DEPLOY_STATUS == 'failure' && 'badge badge-danger' || 'badge badge-secondary' }}">
                    ${{ steps.status-summary.outputs.DEPLOY_STATUS == 'success' && 'PASS' || steps.status-summary.outputs.DEPLOY_STATUS == 'failure' && 'FAIL' || 'SKIPPED' }}
                  </span>
                </p>
                <p>Production deployment to Azure App Service</p>
                ${{ steps.status-summary.outputs.DEPLOY_STATUS == 'success' && '<p>✅ Application successfully deployed to production environment</p>' || '' }}
                ${{ steps.status-summary.outputs.DEPLOY_STATUS == 'failure' && '<p>❌ Deployment failed - check Azure deployment logs</p>' || '' }}
              </div>

              <!-- Final Summary -->
              <div class="summary">
                <h3>🎯 Pipeline Summary</h3>
                ${{ steps.status-summary.outputs.OVERALL_STATUS == 'SUCCESS' }}
                <div style="background: #d4edda; color: #155724; padding: 15px; border-radius: 5px; text-align: center;">
                  <h4 style="margin: 0; color: #155724;">✅ ALL CHECKS PASSED!</h4>
                  <p style="margin: 5px 0 0 0; font-size: 16px;">The application has been successfully deployed to production.</p>
                </div>
                ${{ else }}
                <div style="background: #f8d7da; color: #721c24; padding: 15px; border-radius: 5px; text-align: center;">
                  <h4 style="margin: 0; color: #721c24;">❌ PIPELINE FAILED</h4>
                  <p style="margin: 5px 0 0 0; font-size: 16px;">Some checks failed. Please review the failed jobs below.</p>
                </div>
                ${{ endif }}
              </div>

              <hr>
              <p><strong>🔗 Quick Links:</strong></p>
              <ul>
                <li><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">📋 View Detailed Pipeline Logs</a></li>
                <li><a href="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net">🌐 Visit Deployed Application</a></li>
                <li><a href="https://github.com/${{ github.repository }}">📁 Repository Homepage</a></li>
              </ul>

              <p style="text-align: center; color: #6c757d; margin-top: 30px;">
                <em>This is an automated status report from GitHub Actions CI/CD Pipeline</em>
              </p>
            </div>
          </body>
          </html>
        to: mramzan.workmail@gmail.com
        from: GitHub Actions
        content_type: text/html