name: Simple CI/CD Pipeline with Teams Notifications

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: copro-web-app-zffw1v3o
  DOTNET_VERSION: '8.0.x'
  AZURE_RESOURCE_GROUP: expo-resource-group

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Find project file
      id: find-project
      run: |
        # Find the correct project file path
        $projectFile = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
        echo "PROJECT_PATH=$($projectFile.FullName)" >> $env:GITHUB_ENV
        echo "Found project file: $($projectFile.FullName)"

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build with dotnet
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Test with dotnet
      run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release --no-build --verbosity normal

    - name: Publish with dotnet
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: publish/

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    environment: production
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to production
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

  notify-teams:
    runs-on: ubuntu-latest
    needs: [build-and-test, deploy]
    if: always()
    steps:
    - name: Send Teams notification
      uses: aliencube/microsoft-teams-actions@v0.9.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: 'Deployment Status: ${{ job.status }}'
        summary: |
          Deployment to Azure App Service completed with status: **${{ job.status }}**
          - **Application**: ${{ env.AZURE_WEBAPP_NAME }}
          - **Triggered by**: ${{ github.actor }}
          - **Commit**: ${{ github.sha }}
          - **Build Status**: ${{ needs.build-and-test.result }}
          - **Deploy Status**: ${{ needs.deploy.result }}
        theme-color: '${{ job.status == ''success'' && ''00FF00'' || ''FF0000'' }}'